# import streamlit as st
# import pandas as pd

# # -----------------------------
# # PAGE CONFIG
# # -----------------------------
# st.set_page_config(
#     page_title="Industrial Quality Inspection",
#     page_icon="🏭",
#     layout="wide"
# )

# # -----------------------------
# # LOAD DATA
# # -----------------------------
# df = pd.read_csv("cloud_log.csv")
# df["timestamp"] = pd.to_datetime(df["timestamp"])

# # -----------------------------
# # SIDEBAR FILTERS
# # -----------------------------
# st.sidebar.title("🔧 Filters")

# selected_device = st.sidebar.multiselect(
#     "Select Edge Device",
#     options=df["device_id"].unique(),
#     default=df["device_id"].unique()
# )

# selected_defect = st.sidebar.multiselect(
#     "Select Defect Type",
#     options=df["defect"].unique(),
#     default=df["defect"].unique()
# )

# selected_severity = st.sidebar.multiselect(
#     "Select Severity",
#     options=df["severity"].unique(),
#     default=df["severity"].unique()
# )

# filtered_df = df[
#     (df["device_id"].isin(selected_device)) &
#     (df["defect"].isin(selected_defect)) &
#     (df["severity"].isin(selected_severity))
# ]

# # -----------------------------
# # HEADER
# # -----------------------------
# st.markdown(
#     """
#     <h1 style='text-align:center;'>🏭 Industrial Quality Inspection Dashboard</h1>
#     <p style='text-align:center; font-size:18px; color:grey;'>
#     Edge-to-Cloud Defect Detection & Monitoring System
#     </p>
#     <hr>
#     """,
#     unsafe_allow_html=True
# )

# # -----------------------------
# # KPI SECTION
# # -----------------------------
# total_inspections = len(filtered_df)
# critical_defects = len(filtered_df[filtered_df["severity"] == "HIGH"])
# normal_items = len(filtered_df[filtered_df["defect"].str.lower() == "normal"])
# active_devices = filtered_df["device_id"].nunique()

# k1, k2, k3, k4 = st.columns(4)

# k1.metric("🧪 Total Inspections", total_inspections)
# k2.metric("🚨 Critical Defects", critical_defects)
# k3.metric("✅ Normal Items", normal_items)
# k4.metric("📡 Active Devices", active_devices)

# st.markdown("---")

# # -----------------------------
# # ANALYTICS SECTION
# # -----------------------------
# st.subheader("📊 Inspection Analytics")

# c1, c2 = st.columns(2)

# with c1:
#     st.markdown("**Defect Distribution**")
#     st.bar_chart(filtered_df["defect"].value_counts())

# with c2:
#     st.markdown("**Severity Distribution**")
#     st.bar_chart(filtered_df["severity"].value_counts())

# st.markdown("---")

# # -----------------------------
# # DEVICE LOAD
# # -----------------------------
# st.subheader("📡 Edge Device Activity")
# st.caption("Inspection volume generated by each edge device")

# st.bar_chart(filtered_df["device_id"].value_counts())

# st.markdown("---")

# # -----------------------------
# # RECENT EVENTS TABLE
# # -----------------------------
# st.subheader("📝 Recent Inspection Events")

# pretty_df = filtered_df.sort_values("timestamp", ascending=False).copy()

# pretty_df = pretty_df.rename(columns={
#     "timestamp": "Time",
#     "device_id": "Edge Device",
#     "defect": "Detected Defect",
#     "confidence": "Confidence",
#     "severity": "Severity"
# })

# st.dataframe(
#     pretty_df.head(20),
#     use_container_width=True
# )

# # -----------------------------
# # ALERT SECTION
# # -----------------------------
# st.markdown("---")
# st.subheader("🚨 Alert Summary")

# if critical_defects > 0:
#     st.error(
#         f"{critical_defects} high-severity defect(s) detected.\n\n"
#         "Immediate inspection recommended."
#     )
# else:
#     st.success(
#         "No critical defects detected.\n\n"
#         "System operating within safe thresholds."
#     )

# # -----------------------------
# # SYSTEM STATUS
# # -----------------------------
# st.markdown("---")
# st.subheader("🟢 System Status")

# st.success(
#     "Edge-to-Cloud inspection pipeline is operational.\n\n"
#     "All inspection events are being processed, logged, and visualized in real time."
# )

import streamlit as st
import boto3
import pandas as pd
import time
import plotly.express as px
from botocore.exceptions import ClientError

# --- CONFIGURATION ---
DYNAMODB_TABLE = "WaferInspectionLogs"
REGION = "ap-south-1" 

# ⚠️ SECURITY: Ideally, move these to .streamlit/secrets.toml
AWS_ACCESS_KEY = "AKIAW3MEDYXUAIFPTWPI" 
AWS_SECRET_KEY = "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" 

# --- PAGE SETUP (Must be first) ---
st.set_page_config(
    page_title="WaferSense AI | Industrial Monitor",
    page_icon="🏭",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- CUSTOM CSS FOR "PRO" LOOK ---
st.markdown("""
<style>
    /* Darker background for metrics */
    [data-testid="stMetric"] {
        background-color: #1E1E1E;
        border: 1px solid #333;
        padding: 15px;
        border-radius: 10px;
    }
    
    /* REMOVED: header {visibility: hidden;} 
       Why? This was hiding the sidebar toggle arrow! 
       Instead, we only hide the 'Deploy' button and footer if you want a clean look:
    */
    .stDeployButton {visibility: hidden;}
    footer {visibility: hidden;}

    /* Custom Title Style */
    .title-text {
        font-size: 40px;
        font-weight: 700;
        background: -webkit-linear-gradient(45deg, #00C9FF, #92FE9D);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
    }
</style>
""", unsafe_allow_html=True)

# --- SETUP AWS CLIENTS ---
try:
    dynamodb = boto3.resource(
        'dynamodb',
        region_name=REGION,
        aws_access_key_id=AWS_ACCESS_KEY,
        aws_secret_access_key=AWS_SECRET_KEY
    )
    table = dynamodb.Table(DYNAMODB_TABLE)
except Exception as e:
    st.error(f"Failed to connect to AWS: {e}")

# --- HELPER FUNCTIONS ---
def fetch_data():
    """Fetches and normalizes data from DynamoDB."""
    try:
        response = table.scan()
        items = response.get('Items', [])
        if not items: return pd.DataFrame()

        df = pd.DataFrame(items)

        # Unpack payload if exists
        if 'payload' in df.columns:
            payload_df = pd.json_normalize(df['payload'])
            cols_to_drop = [c for c in payload_df.columns if c in df.columns]
            if cols_to_drop:
                payload_df = payload_df.drop(columns=cols_to_drop)
            df = pd.concat([df.drop('payload', axis=1), payload_df], axis=1)

        # Data Type Cleanup
        if 'timestamp' in df.columns:
            df['timestamp'] = pd.to_datetime(df['timestamp'].astype(str))
            
        return df
    except Exception as e:
        st.error(f"Error reading DynamoDB: {e}")
        return pd.DataFrame()

# --- SIDEBAR CONTROL PANEL ---
with st.sidebar:
    st.title("🎛️ Control Panel")
    
    # 1. Status Indicator
    st.success("● System Online")
    
    # 2. Live Mode Toggle
    if 'auto_refresh' not in st.session_state:
        st.session_state.auto_refresh = False
    
    st.markdown("---")
    st.write("### Monitoring Mode")
    st.session_state.auto_refresh = st.toggle('🟢 Auto-Refresh (Live)', value=st.session_state.auto_refresh)
    
    if st.button("🔄 Manual Refresh", use_container_width=True):
        st.rerun()

    st.markdown("---")
    st.info("**WaferSense AI v1.0**\n\nConnected to: AWS IoT Core\nRegion: ap-south-1")

# --- MAIN DASHBOARD CONTENT ---

# 1. Header Section
col1, col2 = st.columns([3, 1])
with col1:
    st.markdown('<p class="title-text">🏭 Cloud-Centric Wafer Inspection</p>', unsafe_allow_html=True)
with col2:
    # Placeholder for last update time
    st.caption(f"Last Updated: {time.strftime('%H:%M:%S')}")

# Fetch Data
df = fetch_data()

if not df.empty:
    # Sort by time
    df = df.sort_values(by='timestamp', ascending=False)
    
    # --- METRICS ROW ---
    # Calculate Metrics
    total_scanned = len(df)
    defects = df[df['defect'] != 'Good_Wafer']
    defect_count = len(defects)
    defect_rate = (defect_count / total_scanned * 100)
    
    # Advanced: Calculate trend (compare last 10 vs previous 10) - Simplified here
    latest_status = df.iloc[0]['defect']
    
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("📦 Total Wafers", total_scanned, delta=f"+{len(df[df['timestamp'] > (pd.Timestamp.now() - pd.Timedelta(hours=1))])} last hr")
    m2.metric("⚠️ Defect Rate", f"{defect_rate:.1f}%", delta_color="inverse")
    m3.metric("🚨 Active Alerts", len(df[df.get('severity') == 'HIGH']), delta_color="inverse")
    m4.metric("🔍 Latest Result", latest_status, 
             delta="PASS" if latest_status == "Good_Wafer" else "FAIL",
             delta_color="normal" if latest_status == "Good_Wafer" else "inverse")

    st.markdown("---")

    # --- TABS LAYOUT ---
    tab_live, tab_charts, tab_data = st.tabs(["📸 Live Feed", "📊 Analytics", "📋 Data Logs"])

    # === TAB 1: LIVE FEED ===
    with tab_live:
        st.subheader("Real-time Defect Detection")
        
        # Display top 4 recent images in a nice grid
        cols = st.columns(4)
        for i, row in enumerate(df.head(4).itertuples()):
            with cols[i % 4]:
                # Card Container
                with st.container(border=True):
                    # Defect Badge
                    defect_val = getattr(row, 'defect', 'Unknown')
                    color = "green" if defect_val == "Good_Wafer" else "red"
                    st.markdown(f":{color}-background[**{defect_val}**]")
                    
                    # Image
                    img_url = getattr(row, 'image_url', None)
                    if img_url:
                        st.image(img_url, use_container_width=True)
                    else:
                        st.warning("No Image")
                    
                    # Details
                    conf = getattr(row, 'confidence', 0.0)
                    ts = getattr(row, 'timestamp', pd.Timestamp.now())
                    st.caption(f"Confidence: {conf:.2f} | {ts.strftime('%H:%M:%S')}")

    # === TAB 2: ANALYTICS ===
    with tab_charts:
        c1, c2 = st.columns(2)
        
        with c1:
            st.markdown("#### Defect Distribution")
            if 'defect' in df.columns:
                # Plotly Donut Chart
                fig_pie = px.pie(df, names='defect', hole=0.4, color_discrete_sequence=px.colors.sequential.RdBu)
                st.plotly_chart(fig_pie, use_container_width=True)
        
        with c2:
            st.markdown("#### Inspection Activity (Timeline)")
            if 'timestamp' in df.columns:
                # Resample by minute to show activity spikes
                time_df = df.set_index('timestamp').resample('1min').size().reset_index(name='count')
                fig_line = px.area(time_df, x='timestamp', y='count', line_shape='spline', color_discrete_sequence=['#00C9FF'])
                st.plotly_chart(fig_line, use_container_width=True)

    # === TAB 3: DATA LOGS ===
    with tab_data:
        st.markdown("#### Detailed Audit Log")
        
        # Configure columns for a "Pro" look
        st.dataframe(
            df,
            use_container_width=True,
            column_order=["timestamp", "device_id", "defect", "confidence", "severity", "image_url"],
            column_config={
                "timestamp": st.column_config.DatetimeColumn("Time", format="D MMM, HH:mm:ss"),
                "defect": st.column_config.TextColumn("Classification"),
                "confidence": st.column_config.ProgressColumn(
                    "AI Confidence", 
                    format="%.2f", 
                    min_value=0, 
                    max_value=1
                ),
                "severity": st.column_config.Column(
                    "Severity",
                    width="small"
                ),
                "image_url": st.column_config.LinkColumn("Evidence Link")
            },
            hide_index=True
        )

else:
    # Empty State
    st.warning("Waiting for data stream...")
    st.info("💡 Tip: Ensure 'edge_publish.py' is running on your laptop.")

# --- AUTO REFRESH LOGIC ---
if st.session_state.auto_refresh:
    time.sleep(2)
    st.rerun()
