import streamlit as st
import pandas as pd

# -----------------------------
# PAGE CONFIG
# -----------------------------
st.set_page_config(
    page_title="Industrial Quality Inspection",
    page_icon="🏭",
    layout="wide"
)

# -----------------------------
# LOAD DATA
# -----------------------------
df = pd.read_csv("cloud_log.csv")
df["timestamp"] = pd.to_datetime(df["timestamp"])

# -----------------------------
# SIDEBAR FILTERS
# -----------------------------
st.sidebar.title("🔧 Filters")

selected_device = st.sidebar.multiselect(
    "Select Edge Device",
    options=df["device_id"].unique(),
    default=df["device_id"].unique()
)

selected_defect = st.sidebar.multiselect(
    "Select Defect Type",
    options=df["defect"].unique(),
    default=df["defect"].unique()
)

selected_severity = st.sidebar.multiselect(
    "Select Severity",
    options=df["severity"].unique(),
    default=df["severity"].unique()
)

filtered_df = df[
    (df["device_id"].isin(selected_device)) &
    (df["defect"].isin(selected_defect)) &
    (df["severity"].isin(selected_severity))
]

# -----------------------------
# HEADER
# -----------------------------
st.markdown(
    """
    <h1 style='text-align:center;'>🏭 Industrial Quality Inspection Dashboard</h1>
    <p style='text-align:center; font-size:18px; color:grey;'>
    Edge-to-Cloud Defect Detection & Monitoring System
    </p>
    <hr>
    """,
    unsafe_allow_html=True
)

# -----------------------------
# KPI SECTION
# -----------------------------
total_inspections = len(filtered_df)
critical_defects = len(filtered_df[filtered_df["severity"] == "HIGH"])
normal_items = len(filtered_df[filtered_df["defect"].str.lower() == "normal"])
active_devices = filtered_df["device_id"].nunique()

k1, k2, k3, k4 = st.columns(4)

k1.metric("🧪 Total Inspections", total_inspections)
k2.metric("🚨 Critical Defects", critical_defects)
k3.metric("✅ Normal Items", normal_items)
k4.metric("📡 Active Devices", active_devices)

st.markdown("---")

# -----------------------------
# ANALYTICS SECTION
# -----------------------------
st.subheader("📊 Inspection Analytics")

c1, c2 = st.columns(2)

with c1:
    st.markdown("**Defect Distribution**")
    st.bar_chart(filtered_df["defect"].value_counts())

with c2:
    st.markdown("**Severity Distribution**")
    st.bar_chart(filtered_df["severity"].value_counts())

st.markdown("---")

# -----------------------------
# DEVICE LOAD
# -----------------------------
st.subheader("📡 Edge Device Activity")
st.caption("Inspection volume generated by each edge device")

st.bar_chart(filtered_df["device_id"].value_counts())

st.markdown("---")

# -----------------------------
# RECENT EVENTS TABLE
# -----------------------------
st.subheader("📝 Recent Inspection Events")

pretty_df = filtered_df.sort_values("timestamp", ascending=False).copy()

pretty_df = pretty_df.rename(columns={
    "timestamp": "Time",
    "device_id": "Edge Device",
    "defect": "Detected Defect",
    "confidence": "Confidence",
    "severity": "Severity"
})

st.dataframe(
    pretty_df.head(20),
    use_container_width=True
)

# -----------------------------
# ALERT SECTION
# -----------------------------
st.markdown("---")
st.subheader("🚨 Alert Summary")

if critical_defects > 0:
    st.error(
        f"{critical_defects} high-severity defect(s) detected.\n\n"
        "Immediate inspection recommended."
    )
else:
    st.success(
        "No critical defects detected.\n\n"
        "System operating within safe thresholds."
    )

# -----------------------------
# SYSTEM STATUS
# -----------------------------
st.markdown("---")
st.subheader("🟢 System Status")

st.success(
    "Edge-to-Cloud inspection pipeline is operational.\n\n"
    "All inspection events are being processed, logged, and visualized in real time."
)
