import streamlit as st
import pandas as pd

# -----------------------------
# PAGE CONFIG
# -----------------------------
st.set_page_config(
    page_title="Industrial Quality Inspection",
    page_icon="🏭",
    layout="wide"
)

# -----------------------------
# LOAD DATA
# -----------------------------
df = pd.read_csv("cloud_log.csv")

# -----------------------------
# HEADER
# -----------------------------
st.markdown(
    """
    <h1 style='text-align: center;'>🏭 Industrial Quality Inspection Dashboard</h1>
    <p style='text-align: center; font-size:18px;'>
    Real-time monitoring of edge-based defect detection system
    </p>
    <hr>
    """,
    unsafe_allow_html=True
)

# -----------------------------
# KPIs
# -----------------------------
total_inspections = len(df)
high_severity = len(df[df["severity"] == "HIGH"])
normal_items = len(df[df["defect"].str.lower() == "normal"])
active_devices = df["device_id"].nunique()

col1, col2, col3, col4 = st.columns(4)

col1.metric("🧪 Total Inspections", total_inspections)
col2.metric("🚨 Critical Defects", high_severity)
col3.metric("✅ Normal Items", normal_items)
col4.metric("📡 Active Edge Devices", active_devices)

st.markdown("---")

# -----------------------------
# DEFECT OVERVIEW
# -----------------------------
st.subheader("🔍 Defect Overview")

col5, col6 = st.columns(2)

with col5:
    st.markdown("**Defect Distribution**")
    st.bar_chart(df["defect"].value_counts())

with col6:
    st.markdown("**Severity Distribution**")
    st.bar_chart(df["severity"].value_counts())

st.markdown("---")

# -----------------------------
# DEVICE LOAD
# -----------------------------
st.subheader("📡 Edge Device Activity")
st.caption("Number of inspection events generated by each edge device")

st.bar_chart(df["device_id"].value_counts())

st.markdown("---")

# -----------------------------
# RECENT EVENTS (HUMAN READABLE)
# -----------------------------
st.subheader("📝 Recent Inspection Events")

pretty_df = df.copy()
pretty_df["timestamp"] = pd.to_datetime(pretty_df["timestamp"])
pretty_df = pretty_df.sort_values("timestamp", ascending=False)

pretty_df = pretty_df.rename(columns={
    "timestamp": "Time",
    "device_id": "Edge Device",
    "defect": "Detected Defect",
    "confidence": "Confidence Score",
    "severity": "Severity Level"
})

st.dataframe(
    pretty_df.head(15),
    use_container_width=True
)

# -----------------------------
# SYSTEM STATUS
# -----------------------------
st.markdown("---")
st.subheader("🟢 System Status")

st.success(
    "Edge-to-Cloud inspection pipeline is running successfully.\n\n"
    "All inspection events are being processed, stored, and monitored in real time."
)
